### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by Trupal00p** [ChristophBerg/postgresql-unit#10]
How do I install this awesome pg extension? Do I have to build from source or is there a prebuilt package available? I can't seem to find one.

**Comment by ChristophBerg** [comment]
Re: Trupal00p 2017-12-12 <ChristophBerg/postgresql-unit/issues/10@github.com>
> How do I install this awesome pg extension? Do I have to build from source or is there a prebuilt package available? I can't seem to find one.

Hi,

there are packages in Debian and Arch, and at least apt.postgresql.org
and yum.postgresql.org. Otherwise, it's standard PGXS "make && make
install".

Christoph

**Comment by Trupal00p** [comment]
Got it, thank you.

Thanks for your work on this extension, really nicely done.

**Comment by loveencounterflow** [comment]
Here is what I do when installing PostGreSQL and extensions (gleaned from https://www.postgresql.org/download/linux/debian/):

```bash
sudo apt install wget ca-certificates psmisc
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt update
sudo apt install postgresql-10 postgresql-plpython3-10 postgresql-contrib-10 postgresql-10-unit
```

The ppa has a *lot* of packages across a *lot* of PostGreSQL versions. To find what you're looking for without concerning yourself with inane Debian package naming conventions, do e.g.

```bash
apt search '.*postg.*unit' | less -SRN
```
