### ISSUE TITLE
Rounding unit value

### ISSUE THREAD

**Issue by cayman1066** [ChristophBerg/postgresql-unit#11]
Hi Chris,

Again, kudos for the extension!  

Is there a method to round the value returned from a query?  

For example:
`SELECT '25 m'::unit @ 'ft'`
result: 82.0209973753281 ft

I'd like to be able return, for example, 82.0.

Thanks in advance!

**Comment by pvh** [comment]
Use `round()`. See the (documentation)[https://www.postgresql.org/docs/8.1/static/functions-math.html#FUNCTIONS-MATH-FUNC-TABLE] for more detail but in your case this is:

`SELECT round('25 m'::unit @ 'ft', 1);`

**Comment by cayman1066** [comment]
I've tried that first thing and get back:

> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

I've tried every cast method I know to avoid an error, but haven't figured it out.
PG version is 10.1

**Comment by ChristophBerg** [comment]
`round('25 m'::unit @ 'ft', 1)` is two problems in one, namely that there is no rounding operator for unit yet, and that the output of the @ operator is of type cstring (i.e. neither unit nor anything else convertible to numbers).
The first one is easy to fix. For the second one, we probably need a round() function that takes 3 arguments as in `round('25 m'::unit, 'ft', 1)`. Not sure if there's a good way to preserve @ as operator in that use case.

**Comment by cayman1066** [comment]
Thanks, Christoph.  You're right in saying that there's likely no easy way to preserve the @ operator.  The 3 argument round() function you suggest makes sense. I'll handle it in the meantime by massaging the result post-query in my application logic, but will leave myself a @todo note in my code to come back to it once a solution is in place.  As always, thanks again for an excellent extension.

**Comment by ChristophBerg** [comment]
@cayman1066: It turns out the @-with-rounding functionality is already present via `extra_float_digits`:
```
# set extra_float_digits = -12;
# select '25m'::unit @ 'ft';
 82 ft
# set extra_float_digits = -11;
# select '25m'::unit @ 'ft';
 82.02 ft
```
It's a bit awkward to use, and it counts total number of digits, not digits after the decimal point, but it's a start. I'll likely add more rounding functions once I have thought a bit more about which ones would be useful. (Should round('12345m', 2) return 12km, 12.34km, or 12345.00km? Or should there be several flavors of rounding functions?)
