### ISSUE TITLE
Run on Windows?

### ISSUE THREAD

**Issue by lumberg72** [ChristophBerg/postgresql-unit#16]
Hi, looks like a great project... exactly what I need.
However, I would need it to run on both Windows and CentOS. I don't see either of these mentioned in the doc. Is it reasonably possible? Maybe some documentation I'm missing?
(I don't know much about compiling C, so even if it's technically possible, I would be pretty lost.)
Thanks

**Comment by ChristophBerg** [comment]
Hi,
it's really just C code, with some flex and bison processing. You'll need to get a C compiler and flex/bison installed to build it yourself.
For CentOS, packages are available via yum.postgresql.org, I'd suggest using these, for windows there are no pre-compiled packages.
