### ISSUE TITLE
temperature conversion in postgresql table column is not correct.

### ISSUE THREAD

**Issue by rahulworld** [ChristophBerg/postgresql-unit#18]
Data in coumn
![humidity](https://user-images.githubusercontent.com/15066782/43017243-05ff8c16-8c73-11e8-8f6a-85acb3864f9b.png)
after conversion degree Celsius to Fahrenheit Getting
![fahrenheit](https://user-images.githubusercontent.com/15066782/43017312-4547bab0-8c73-11e8-8e36-b6488d9313da.png)

**Comment by zr40** [comment]
What is the query you used to get this result?

**Comment by rahulworld** [comment]
select temp*'°C'::unit@@'°F' as temp from obs;

**Comment by zr40** [comment]
`temp*'°C'::unit` is incorrect. `°C` without a number represents the difference in temperature by one degree on the Celsius scale, which is equal to 1 K. Multiplying that by 25 results in 25 K, not 25 °C.

Instead, do `(temp::text || '°C')::unit` to get the desired result.

**Comment by rahulworld** [comment]
It Worked.
Thanks @zr40

**Comment by ChristophBerg** [comment]
You can also use the `celsius` function: `SELECT celsius(28.3) @ '°F';`
