### ISSUE TITLE
Curious, why GPL?

### ISSUE THREAD

**Issue by jdatcmd** [ChristophBerg/postgresql-unit#2]
Versus the PostgreSQL license?

**Comment by jdatcmd** [comment]
On 11/06/2016 02:09 AM, Christoph Berg wrote:
> ... why not? I don't think this module would realistically be eligible
> for inclusion in PostgreSQL core, so I don't see the imminent need for a
> different license.
>
> Do you have a use case where a non-copyleft license would be beneficial?

The only concern I would have (I am not anti-gpl) is that I believe by 
using the GPL, nobody can realistically incorporate your work (which is 
awesome btw) as a distribution with PostgreSQL.

Consider the snap packages CMD has been working on. I think it would be 
awesome to have your work automatically included and enabled as part of 
the distribution. Now, that isn't an issue for us because we will leave 
everything open source but it could be an issue downstream for someone 
who wants to take our work (or even EDB/OpenSCG/PostgresPro etc...) and 
close it up.

Just a thought. Thanks for the great work.

Sincerely,

JD


-- 
Command Prompt, Inc.                  http://the.postgres.company/
                         +1-503-667-4564
PostgreSQL Centered full stack support, consulting and development.
Everyone appreciates your honesty, until you are honest with them.
Unless otherwise stated, opinions are my own.

**Comment by ChristophBerg** [comment]
Hi,

thanks for the input. I don't think it's a real issue because there's other extensions using GPL (postgis!), which I think are already shipped by the EDB/... installers. The infrastructure is already in place.

Cheers,
Christoph
