### ISSUE TITLE
Support IEC units

### ISSUE THREAD

**Issue by derekmorr** [ChristophBerg/postgresql-unit#3]
Would you consider supporting IEC units for bytes? I.e., Kibibytes, Mebibytes, Gibibyte, etc? These are the base-two sizes, and are commonly used.

**Comment by ChristophBerg** [comment]
This has been on the extended TODO list from the beginning. I'll see to make it happen over the next days. Thanks for bringing it up!

**Comment by derekmorr** [comment]
Thanks for the fast turnaround!
