### ISSUE TITLE
Missing units for entropy?

### ISSUE THREAD

**Issue by zx80** [ChristophBerg/postgresql-unit#7]
Shannon & Hart are not to be supported?

  psql> SELECT UNIT '1 shannon'; -- Sh Hart
  ERROR:  unit "shannon" is not known

But bit & nat are supported.

**Comment by ChristophBerg** [comment]
The available units are almost all from GNU units' definitions.units file. Shannon is indeed not in there - it seems to be mostly the same as bit to me, so not sure if it's worth inserting here. Maybe talk to the GNU units maintainer instead? (Unfortuantely, they don't seem to have a public git repository.)

**Comment by zx80** [comment]
Shannon is indeed a synonymous for bit.
It think it is worth adding a unit named after the founder of information theory, just like there
is Volt, Ampere and others:-)
The "hartley" is indeed there, although not with symbol "Hart".

**Comment by ChristophBerg** [comment]
I've taken a look at this again and decided not to add the units. Bit and Shannon are only almost the same, with subtle differences in information theory with non-uniform probability distribution. The fact that bit is crudely defined as 1/8B doesn't make adding more information theory units more attractive, and then, I'd doubt there would be many users of the new entries.
If you need the definitions, please extend the table locally, as explained in the docs.
Thanks for the suggestion though, your input is much appreciated!
