### ISSUE TITLE
Bit shown with 1000 units

### ISSUE THREAD

**Issue by zx80** [ChristophBerg/postgresql-unit#8]
Byte units are shown in 1000 units around B, so that 1 bit is... 125 mB (millibytes).

Although this makes some sense, it is surprising for the computer aware user:-)

Maybe for these the 1024 powers multipliers (Ki, ...) could be chosen instead, and "bit" could also be considered as a 1/8 unit candidate for Byte?

**Comment by ChristophBerg** [comment]
This is already an option, though by default off:
```
# set unit.byte_output_iec = on;
# select '1024 B'::unit;
 unit  
───────
 1 KiB
```

**Comment by zx80** [comment]
Argh, Sorry RTFM!
