### ISSUE TITLE
Installation problems with PG 9.6.x compiled from source

### ISSUE THREAD

**Issue by cayman1066** [ChristophBerg/postgresql-unit#9]
Hi Chris,

I'm trying to install your postgresql-unit extension on to an Ubuntu 16.04 server with PostgreSQL 9.6.1 compiled from source code.  When I run 'sudo make install', I receive the following errors:

`Makefile:18: /usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory`

`awk: fatal: cannot open file '/usr/include/postgresql/10/server/pg_config.h' for reading (No such file or directory)`

`/bin/sh: 1: [: -ge: unexpected operator
`
`make: *** No rule to make target '/usr/lib/postgresql/10/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.`

It appears to be looking for a version of PostgreSQL 10, and that installed via aptitude instead of from source.   My pg_config.h and pgxs.mk files are located:

./src/postgresql-9.6.1/src/include/pg_config.h
./src/postgresql-9.6.1/src/makefiles/pgxs.mk

I'm not adept enough with make to have it look for elsewhere for the files.
Any suggestions for me?

Thanks in advance!

**Comment by ChristophBerg** [comment]
Try `make install PG_CONFIG=/usr/lib/postgresql/9.6/bin/pg_config`.

**Comment by cayman1066** [comment]
Sweet.  That was it, or in my case:
sudo make install PG_CONFIG=/usr/local/pgsql/bin/pg_config

Thanks for the quick response, Christoph
